spring.application.name=TiendaGenerica-Grupo10-backend
spring.datasource.url=jdbc:mysql://tienda-generica-db.c8z242ws0swx.us-east-1.rds.amazonaws.com:3306/tienda_generica
spring.datasource.username=admin
spring.datasource.password=XsRl9484E9LUc01gbiX3#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=8088